# Generated by Django 3.2.4 on 2021-06-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
